export const MOCKS = {
  undefinedMock: undefined,
  nullMock: null,
  booleanFalseMock: false,
  booleanTrueMock: true,
  number0Mock: 0,
  number42Mock: 42,
  number42p525Mock: 42.525,
  numberMinus42Mock: -42,
  numberMinus42p525Mock: -42.525,
  numberNaNMock: NaN,
  numberInfinityMock: Infinity,
  stringEmptyMock: '',
  string42Mock: '42',
  string42p525Mock: '42.525',
  stringLatinMock: 'John Doe 123',
  stringNonlatinMock: '시험',
  stringEmojiMock: '💥',
  arrayEmptyMock: [],
  arrayUndefinedMock: [undefined],
  arrayFalse42JohnDoeMock: [42, false, 'John Doe'],
  objectEmptyMock: {},
  objectFooUndefinedMock: { foo: undefined },
  objectFoo42Mock: { foo: 42 },
  objectFooBarMock: { foo: 'bar' },
  objectMathMock: Math,
  objectErrorMock: new Error('Hello world!'),
};
